### PR TITLE
Return list of cx friendly 4xx errors for indexing custom rules

### LINKED ISSUE #863: [BUG] Index Rules API doesn't return the details of the errors while creating sigma rules
**What is the bug?**

**How can one reproduce the bug?**
1. Go to 'Detection rules page'
2. Click on 'Create rules button'
3. Choose the YAML editor format and enter the below input:
```
{
    "title": "Moriya Rootkit",
    "description": "Detects the use of Moriya rootkit as described in the securelist's Operation TunnelSnake report",
    "status": "experimental",
    "author": "Bhabesh Raj",
    "date": "2021/05/06",
    "modified": "2021/11/30",
    "references": [
        "https://securelist.com/operation-tunnelsnake-and-moriya-rootkit/101831"
    ],
    "tags": [
        "attack.persistence",
        "attack.privilege_escalation",
        "attack.t1543.003"
    ],
    "logsource": {
        "product": "custom-log-type1"
    },
    "detection": {
        "selection": {
            "Provider_Name": "Service Control Manager",
            "EventID": 7045,
            "ServiceName": "ZzNetSvc"
        },
        "condition": "selection"
    },
    "level": "test",
    "falsepositives": [
        "Unknown"
    ]
}
```
5. The error returned doesn't provide the details about the level attribute being wrong. The backend API output looks like:
```
{
    "error": {
        "root_cause": [
            {
                "type": "security_analytics_exception",
                "reason": "Unknown error"
            }
        ],
        "type": "security_analytics_exception",
        "reason": "Unknown error",
        "caused_by": {
            "type": "exception",
            "reason": "org.opensearch.action.search.SearchPhaseExecutionException: "
        }
    },
    "status": 400
}
```

**What is the expected behavior?**
The output of the API should return the list of cx errors which can be interpreted by the frontend to display the right behavior on the UI.

**What is your host/environment?**
 - Version [e.g. 22] 2.11
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

### PR DESCRIPTION
**Pull request by goyamegh**
### Description
This PR caters to return the list of errors in the form of Security Analytics Exception along with a detailed message. Changes involved are:
1. Catch the enum conversion exceptions for attributes status, log source, detections and level in sigma rules.
2. Make changes to provide consistent behavior (by creating a new exception of list of errors) in case the flag collectErrors is flipped to false for future use-cases.

To provide an example, the format of exception **before** was:
```
{
    "error": {
        "root_cause": [
            {
                "type": "security_analytics_exception",
                "reason": "Unknown error"
            }
        ],
        "type": "security_analytics_exception",
        "reason": "Unknown error",
        "caused_by": {
            "type": "exception",
            "reason": "org.opensearch.action.search.SearchPhaseExecutionException: "
        }
    },
    "status": 400
}
```

After these changes, the exception would be:
```
{
    "error": {
        "root_cause": [
            {
                "type": "security_analytics_exception",
                "reason": "{\"SigmaIdentifierError\":\"Sigma rule identifier must be an UUID\",\"SigmaLevelError\":\"Value of level not correct\"}"
            }
        ],
        "type": "security_analytics_exception",
        "reason": "{\"SigmaIdentifierError\":\"Sigma rule identifier must be an UUID\",\"SigmaLevelError\":\"Value of level not correct\"}",
        "caused_by": {
            "type": "exception",
            "reason": "java.util.Arrays$ArrayList: {\"SigmaIdentifierError\":\"Sigma rule identifier must be an UUID\",\"SigmaLevelError\":\"Value of level not correct\"}"
        }
    },
    "status": 400
}
```

### Issues Resolved
#863
 
### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: src/main/java/org/opensearch/securityanalytics/rules/backend/QueryBackend.java [hunk 1]
```diff
@@ -104,6 +95,7 @@ public List<Object> convertRule(SigmaRule rule) throws SigmaError {
 
             this.queryFields.putAll(this.ruleQueryFields);
         } catch (SigmaError ex) {
+            // TODO: Merge the exception to the original list of errors coming from SigmaRule.java and use the same throwing logic
```
Comment (eirsep) [inline src/main/java/org/opensearch/securityanalytics/rules/backend/QueryBackend.java:98]: plz resolve TODO

**Comment by eirsep** [comment]
plz udpate descirption

File: src/main/java/org/opensearch/securityanalytics/util/SecurityAnalyticsException.java [hunk 2]
```diff
@@ -68,14 +68,17 @@ public static OpenSearchException wrap(OpenSearchException ex) {
...
+     */
     public static OpenSearchException wrap(List<Exception> ex) {
         try {
             RestStatus status = RestStatus.BAD_REQUEST;
 
             XContentBuilder builder = XContentFactory.jsonBuilder().startObject();
             for (Exception e: ex) {
                 builder.field("error", e.getMessage());
-                log.error("Security Analytics error:", e);
+                log.warn("[CUSTOMER ERROR] Security Analytics error:", e);
```
Comment (eirsep) [inline src/main/java/org/opensearch/securityanalytics/util/SecurityAnalyticsException.java:81]: why did we change log message level? plz revert

Why did we even change the text and add customer error. unnecessary and confusing?

File: src/main/java/org/opensearch/securityanalytics/util/SecurityAnalyticsException.java [hunk 3]
```diff
@@ -68,14 +68,17 @@ public static OpenSearchException wrap(OpenSearchException ex) {
         return new SecurityAnalyticsException(friendlyMsg, status, new Exception(String.format(Locale.getDefault(), "%s: %s", ex.getClass().getName(), ex.getMessage())));
     }
 
+    /*
+     * Intended for a curated list of Customer validation exceptions (4xx)
```
Comment (eirsep) [inline src/main/java/org/opensearch/securityanalytics/util/SecurityAnalyticsException.java:72]: what about 5xx and other HTTP errors??

File: src/main/java/org/opensearch/securityanalytics/util/SecurityAnalyticsException.java (hunk 2 above)
Comment (goyamegh) [reply src/main/java/org/opensearch/securityanalytics/util/SecurityAnalyticsException.java:81]: This is intentional to be a warning message. All customer related errors need not be part of error logs as they are not system issues. 
Also, this error was modified to convey that this is a client side exception to help with debugging.

Feel free to recommend a more explicit way to differentiate between client-side and server-side errors.

File: src/main/java/org/opensearch/securityanalytics/rules/backend/QueryBackend.java (hunk 1 above)
Comment (goyamegh) [reply src/main/java/org/opensearch/securityanalytics/rules/backend/QueryBackend.java:98]: This will be taken up as a fast-follower, as this requires a more elaborate set of changes.

**Review by eirsep — CHANGES_REQUESTED** [review]

File: src/main/java/org/opensearch/securityanalytics/rules/exceptions/SigmaErrorList.java [hunk 4]
```diff
@@ -0,0 +1,24 @@
...
+ * Copyright OpenSearch Contributors
+ * SPDX-License-Identifier: Apache-2.0
+ */
+package org.opensearch.securityanalytics.rules.exceptions;
+
+import java.util.ArrayList;
+import java.util.List;
+
+public class SigmaErrorList extends Exception {
+    private final List<SigmaError> errorList;
```
[the remark this answers is not in the document]
Comment (goyamegh) [reply src/main/java/org/opensearch/securityanalytics/rules/exceptions/SigmaErrorList.java:11]: The idea was to ensure backward compatibility. Any customer using this exception should not see exceptions because of our changes. We can discuss this and refactor accordingly as needed.

File: src/main/java/org/opensearch/securityanalytics/rules/backend/QueryBackend.java [hunk 5]
```diff
@@ -266,5 +258,5 @@ public Object convertConditionVal(ConditionValueExpression condition) throws Sig
 
 /*   public abstract Object convertConditionValQueryExpr(ConditionValueExpression condition);*/
 
-    public abstract AggregationQueries convertAggregation(AggregationItem aggregation) throws SigmaError;
```
[the remark this answers is not in the document]
Comment (goyamegh) [reply src/main/java/org/opensearch/securityanalytics/rules/backend/QueryBackend.java:269]: It was not being thrown by the concrete method, hence redundant and needed cleanup.

File: src/main/java/org/opensearch/securityanalytics/model/Rule.java [hunk 6]
```diff
@@ -475,8 +477,9 @@ public boolean isAggregationRule() {
         return aggregationQueries != null && !aggregationQueries.isEmpty();
     }
 
-    public List<AggregationItem> getAggregationItemsFromRule () throws SigmaError {
+    public List<AggregationItem> getAggregationItemsFromRule () throws SigmaErrorList, SigmaConditionError {
```
Comment (sbcd90) [inline src/main/java/org/opensearch/securityanalytics/model/Rule.java:480]: can we keep just `SigmaError` or `SigmaErrorList`? it creates confusion to read code with both these 2 exceptions.

File: src/main/java/org/opensearch/securityanalytics/model/Rule.java [hunk 7]
```diff
@@ -475,8 +477,9 @@ public boolean isAggregationRule() {
...
         SigmaRule sigmaRule = SigmaRule.fromYaml(rule, true);
+        // TODO: Check if there are cx errors from the rule created and throw errors
```
Comment (engechas) [inline src/main/java/org/opensearch/securityanalytics/model/Rule.java:482]: Minor: could we create GH issues for TODOs and link them? Would help to track this sort of thing

File: src/main/java/org/opensearch/securityanalytics/rules/backend/QueryBackend.java (hunk 1 above)
Comment (engechas) [reply src/main/java/org/opensearch/securityanalytics/rules/backend/QueryBackend.java:98]: Same comment as above about creating/linking an issue

File: src/main/java/org/opensearch/securityanalytics/rules/exceptions/SigmaError.java [hunk 8]
```diff
@@ -6,7 +6,7 @@
 
 public class SigmaError extends Exception {
 
-    private String message;
+    private final String message;
```
Comment (engechas) [inline src/main/java/org/opensearch/securityanalytics/rules/exceptions/SigmaError.java:9]: Nice, we should continue slowly cleaning the repo to follow best practices as we encounter this sort of stuff

File: src/main/java/org/opensearch/securityanalytics/rules/exceptions/SigmaErrorList.java [hunk 9]
```diff
@@ -0,0 +1,24 @@
+/*
+ * Copyright OpenSearch Contributors
+ * SPDX-License-Identifier: Apache-2.0
+ */
+package org.opensearch.securityanalytics.rules.exceptions;
+
+import java.util.ArrayList;
+import java.util.List;
+
+public class SigmaErrorList extends Exception {
```
Comment (engechas) [inline src/main/java/org/opensearch/securityanalytics/rules/exceptions/SigmaErrorList.java:10]: Naming nit: maybe CompositeSigmaError. The name `SigmaErrorList` does not imply its an exception imo

Comment (engechas) [reply src/main/java/org/opensearch/securityanalytics/rules/exceptions/SigmaErrorList.java:10]: We could also extend SigmaError rather than Exception to avoid changing the checked exceptions throughout the code.

Semi-related - using checked exceptions is a bad practice. Is there a downside of extending a RuntimeException rather than a base Exception? I'm not sure if there are considerations specific to the larger OpenSearch exception handling

File: src/main/java/org/opensearch/securityanalytics/util/SecurityAnalyticsException.java (hunk 2 above)
Comment (engechas) [reply src/main/java/org/opensearch/securityanalytics/util/SecurityAnalyticsException.java:81]: I'd still advocate for using `error` level over warning for exceptions. We should be able to distinguish user vs server errors with the RestStatus ultimately returned for the API call.

I would also advocate against using prefixes in the exceptions in general. If we do want to keep it, let's change `CUSTOMER` to `USER`.

File: src/main/java/org/opensearch/securityanalytics/model/Rule.java (hunk 6 above)
Comment (goyamegh) [reply src/main/java/org/opensearch/securityanalytics/model/Rule.java:480]: We cannot get away with SigmaError as it is a base class for all Sigma related errors. To avoid confusion, I have renamed the new list object to SigmaCompositeError.

File: src/main/java/org/opensearch/securityanalytics/rules/exceptions/SigmaErrorList.java (hunk 9 above)
Comment (goyamegh) [reply src/main/java/org/opensearch/securityanalytics/rules/exceptions/SigmaErrorList.java]: We cannot extend SigmaError, as that would mean that we can have one message string in the exception. This we will append after we have collected all the exceptions in a list, and then finally convert it to SecurityAnalyticsException. 

Further, we can't get away with SigmaError class, as this is a base class for all sigma errors.

Made the semantic changes as suggested.

File: src/main/java/org/opensearch/securityanalytics/correlation/Enginecopy.java [hunk 10]
```diff
@@ -0,0 +1,552 @@
+///*
```
[the remark this answers is not in the document]
Comment (goyamegh) [reply src/main/java/org/opensearch/securityanalytics/correlation/Enginecopy.java]: Removed.

**Review by engechas — DISMISSED** [review]

**Review by jowg-amazon — APPROVED** [review]

File: src/main/java/org/opensearch/securityanalytics/model/Rule.java (hunk 7 above)
Comment (eirsep) [reply src/main/java/org/opensearch/securityanalytics/model/Rule.java:481]: +1

**Review by engechas — APPROVED** [review]

**Review by jowg-amazon — APPROVED** [review]

**Comment by jowg-amazon** [comment]
Should get the CI's passing one round before merging

**Review by jowg-amazon — APPROVED** [review]

**Review by engechas — APPROVED** [review]
