### PR TITLE
[Bug] Fixed ListIOCs number of findings cap.

### LINKED ISSUE #1191: [BUG] ListIOCsAPI total hits, and findings count per IOC are incorrect
**What is the bug?**
The "total" count returned by the ListIOCs API currently maxes at 10,000. This count should be the total number of IOCs that match the query.

The "numFindings" count for each IOC also currently maxes at 10,000. The query used to collect this count should ideally be refactored to an aggregation. Only the count of findings for each IOC needs to be returned.

### PR DESCRIPTION
**Pull request by AWSHurneyt**
### Description
1. Fixed total IOCs count capping at 10,000.
2. Fixed number of findings per IOC capping at 10,000.

### Related Issues
Resolves #1191 

### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [x] Commits are signed per the DCO using `--signoff`.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/security-analytics/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by AWSHurneyt** [comment]
The security test workflow has been failing ([example](https://github.com/opensearch-project/security-analytics/actions/runs/11473167781/job/31926938474?pr=1372)), and will be investigated separately.

**Review by jowg-amazon — DISMISSED** [review]

File: src/test/java/org/opensearch/securityanalytics/resthandler/ListIOCsRestApiIT.java [hunk 1]
```diff
@@ -126,4 +133,122 @@ public void testListIOCsBySearchString() throws IOException {
     }
 
     // TODO: Implement additional tests using various query param combinations
+
+    public void testListIOCsNumFindings() throws Exception {
```
Comment (eirsep) [inline src/test/java/org/opensearch/securityanalytics/resthandler/ListIOCsRestApiIT.java:137]: can we add another test where there are 100 iocs and findings index doesnt exist?

File: src/main/java/org/opensearch/securityanalytics/threatIntel/transport/TransportListIOCsAction.java [hunk 2]
```diff
@@ -322,6 +253,81 @@ public void onFailure(Exception e) {
...
+                            log.error(
+                                    () -> new ParameterizedMessage("Failed to parse IOC doc from hit {}", hit.getId()), e
+                            );
+                        }
+                    });
+
+            // Create an aggregation query that will group by the IOC IDs in the findings
+            SearchSourceBuilder findingsCountSourceBuilder = new SearchSourceBuilder()
+                    .version(true)
+                    .seqNoAndPrimaryTerm(true)
```
Comment (eirsep) [inline src/main/java/org/opensearch/securityanalytics/threatIntel/transport/TransportListIOCsAction.java:283]: why do we need seq and primary term?

File: src/main/java/org/opensearch/securityanalytics/threatIntel/transport/TransportListIOCsAction.java [hunk 3]
```diff
@@ -216,6 +219,7 @@ private void listIocs(List<String> iocIndices) {
                     .version(true)
                     .seqNoAndPrimaryTerm(true)
```
Comment (eirsep) [inline src/main/java/org/opensearch/securityanalytics/threatIntel/transport/TransportListIOCsAction.java:220]: can we remove seqno and primary term and version?

File: src/main/java/org/opensearch/securityanalytics/threatIntel/transport/TransportListIOCsAction.java (hunk 2 above)
Comment (eirsep) [reply src/main/java/org/opensearch/securityanalytics/threatIntel/transport/TransportListIOCsAction.java:283]: can we remove seqno and primary term and version?

File: src/test/java/org/opensearch/securityanalytics/resthandler/ListIOCsRestApiIT.java (hunk 1 above)
Comment (AWSHurneyt) [reply src/test/java/org/opensearch/securityanalytics/resthandler/ListIOCsRestApiIT.java:234]: Added `testListIOCsWithNoFindingsIndex` test case.

File: src/main/java/org/opensearch/securityanalytics/threatIntel/transport/TransportListIOCsAction.java (hunk 2 above)
Comment (AWSHurneyt) [reply src/main/java/org/opensearch/securityanalytics/threatIntel/transport/TransportListIOCsAction.java]: Agreed; they're extraneous in this context. Removed.

**Review by eirsep — APPROVED** [review]

**Review by jowg-amazon — APPROVED** [review]
