### PR TITLE
[BUG] ArrayIndexOutOfBoundsException for inconsistent detector index behavior 

### LINKED ISSUE #842: [BUG] ArrayIndexOutOfBoundsException for inconsistent detector index behavior
**What is the bug?**
A clear and concise description of the bug.

**How can one reproduce the bug?**
1. Go to Security Analytics and create a detector.
2. Follow up with correlation rules
3. See errors in the logs: 

```
[2024-02-07T15:38:48,297][ERROR][o.o.s.u.SecurityAnalyticsException] [25c1ef95a376d5b13cdbde33eaa50bbe] Security Analytics error:
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
        at org.opensearch.search.SearchHits.getAt(SearchHits.java:171)
        at org.opensearch.securityanalytics.transport.TransportCorrelateFindingAction$AsyncCorrelateFindingAction$1.onResponse(TransportCorrelateFindingAction.java:269)
        at org.opensearch.securityanalytics.transport.TransportCorrelateFindingAction$AsyncCorrelateFindingAction$1.onResponse(TransportCorrelateFindingAction.java:259)
        at org.opensearch.action.support.TransportAction$1.onResponse(TransportAction.java:113)
        at org.opensearch.action.support.TransportAction$1.onResponse(TransportAction.java:107)
        at org.opensearch.performanceanalyzer.action.PerformanceAnalyzerActionListener.onResponse(PerformanceAnalyzerActionListener.java:55)
        at org.opensearch.action.support.TimeoutTaskCancellationUtility$TimeoutRunnableListener.onResponse(TimeoutTaskCancellationUtility.java:132)
        at org.opensearch.action.search.TransportSearchAction.lambda$executeRequest$0(TransportSearchAction.java:453)
        at org.opensearch.core.action.ActionListener$1.onResponse(ActionListener.java:82)
        at org.opensearch.core.action.ActionListener$5.onResponse(ActionListener.java:268)
        at org.opensearch.action.search.AbstractSearchAsyncAction.sendSearchResponse(AbstractSearchAsyncAction.java:707)
        at org.opensearch.action.search.ExpandSearchPhase.run(ExpandSearchPhase.java:132)
        at org.opensearch.action.search.SearchPhase.recordAndRun(SearchPhase.java:59)
        at org.opensearch.action.search.AbstractSearchAsyncAction.executePhase(AbstractSearchAsyncAction.java:456)
        at org.opensearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:440)
        at org.opensearch.action.search.FetchSearchPhase.moveToNextPhase(FetchSearchPhase.java:298)
        at org.opensearch.action.search.FetchSearchPhase.lambda$innerRun$1(FetchSearchPhase.java:138)
        at org.opensearch.action.search.CountedCollector.countDown(CountedCollector.java:66)
        at org.opensearch.action.search.CountedCollector.onFailure(CountedCollector.java:85)
        at org.opensearch.action.search.FetchSearchPhase$2.onFailure(FetchSearchPhase.java:257)
        at org.opensearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:75)
        at org.opensearch.action.search.SearchTransportService$ConnectionCountingHandler.handleException(SearchTransportService.java:753)
        at org.opensearch.transport.TransportService$6.handleException(TransportService.java:903)
        at org.opensearch.security.transport.SecurityInterceptor$RestoringTransportResponseHandler.handleException(SecurityInterceptor.java:418)
        at org.opensearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1526)
        at org.opensearch.transport.InboundHandler.lambda$handleException$3(InboundHandler.java:438)
        at org.opensearch.common.util.concurrent.OpenSearchExecutors$DirectExecutorService.execute(OpenSearchExecutors.java:412)
        at org.opensearch.transport.InboundHandler.handleException(InboundHandler.java:436)
        at org.opensearch.transport.InboundHandler.handlerResponseError(InboundHandler.java:428)
        at org.opensearch.transport.InboundHandler.messageReceived(InboundHandler.java:166)
        at org.opensearch.transport.InboundHandler.inboundMessage(InboundHandler.java:123)
        at org.opensearch.transport.TcpTransport.inboundMessage(TcpTransport.java:770)
```    

**What is the expected behavior?**
The call should go through with the failure that detector is not found for given monitor id.

**What is your host/environment?**
 - Plugins SAP with Correlations

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

### PR DESCRIPTION
**Pull request by goyamegh**
### Description
Fixes the following issues:
1. In case the detector search request returns empty hits, the exception should be gracefully handled and checked before.
2. Case when multiple detectors are present and we are fetching only one detector.
 
### Issues Resolved
#842  
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: src/main/java/org/opensearch/securityanalytics/transport/TransportCorrelateFindingAction.java [hunk 1]
```diff
@@ -261,7 +261,8 @@ public void onResponse(SearchResponse response) {
                         }
 
                         SearchHits hits = response.getHits();
-                        if (hits.getTotalHits().value == 1) {
+                        // Detectors Index hits count could be more even if we fetch one
```
Comment (eirsep) [inline src/main/java/org/opensearch/securityanalytics/transport/TransportCorrelateFindingAction.java:264]: just curious why can it >1 ??

File: src/main/java/org/opensearch/securityanalytics/transport/TransportCorrelateFindingAction.java [hunk 2]
```diff
@@ -271,6 +272,9 @@ public void onResponse(SearchResponse response) {
                                 );
                                 Detector detector = Detector.docParse(xcp, hit.getId(), hit.getVersion());
                                 joinEngine.onSearchDetectorResponse(detector, finding);
+                            } catch (ArrayIndexOutOfBoundsException e) {
```
Comment (eirsep) [inline src/main/java/org/opensearch/securityanalytics/transport/TransportCorrelateFindingAction.java:275]: why are we catching ArrayIndexOutOfBoundsException also if we are adding check on array size???
can we instead add an error log in the IOException catch>

**Review by eirsep — CHANGES_REQUESTED** [review]

File: src/main/java/org/opensearch/securityanalytics/transport/TransportCorrelateFindingAction.java (hunk 2 above)
Comment (goyamegh) [reply src/main/java/org/opensearch/securityanalytics/transport/TransportCorrelateFindingAction.java:275]: Removed.

File: src/main/java/org/opensearch/securityanalytics/transport/TransportCorrelateFindingAction.java (hunk 1 above)
Comment (goyamegh) [reply src/main/java/org/opensearch/securityanalytics/transport/TransportCorrelateFindingAction.java:264]: Keeping it >1 in case we remove filters and the number of hits are more than 1.

**Review by engechas — APPROVED** [review]
